### PR TITLE
Added missing barcode types

### PR DESCRIPTION
**Pull request by blargity**
We had a need to use EAN8 format, and I noticed it wasn't bundled in this package. These additional formats came from JsBarcode here: https://github.com/lindell/JsBarcode/tree/master/src/barcodes. 

I also added validation on the format PropType to make it easier to know which formats are supported and what string to use to render them.

The changes to CODE128_AUTO are just whitespace changes, but I figured it made sense to just use the original format of the file so when we pull in the latest changes from JsBarcode the diff will be easier to read.

Let me know if you have any questions/changes. Happy to help!

### CODE REVIEW

**Comment by wonsikin** [comment]
@blargity Thank you for your PR! I'm glad you can help me make this repository more perfect.

Do you have any perfect workflow that I can check a package before it publish?

**Comment by blargity** [comment]
Probably the best way is to set up unit testing and CI. In this case, since most of the code comes from JsBarcode, it's probably easiest if we just depend on them as a Git submodule to pull their code in. Then we'd only need to unit test our code and could depend on [their tests](https://github.com/lindell/JsBarcode/tree/master/test) for their stuff.

I've used [TravisCI](https://travis-ci.org/) with open source projects in the past to great effect.

**Comment by blargity** [comment]
Also, if you could bump the version number and push a release to NPM that'd be awesome!

**Comment by wonsikin** [comment]
@blargity Thank you! I have pushed it.

**Pull request merged**
