### PR TITLE
replace react-native-svg with ART

### PR DESCRIPTION
**Pull request by koenpunt**
since react-native ships with it's own vector drawing library, why use an external dependency?

This merge request removes `react-native-svg` as a dependency, and implements the rendering using [React Native's ART](https://github.com/facebook/react-native/tree/master/Libraries/ART) instead.

### CODE REVIEW

**Comment by wonsikin** [comment]
You are genius. But I got some problems when I try to run the Example.
### Android
In order to run on the android, I have to modify the `Example/android/app/src/main/java/com/example/MainApplication.java`:
```git
   private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
     @Override
-    protected boolean getUseDeveloperSupport() {
+    public boolean getUseDeveloperSupport() {
       return BuildConfig.DEBUG;
     }
```

When I try to run example in the latest react native version, I got the error [UnableToResolveError: Unable to resolve module `AccessibilityInfo`](https://github.com/facebook/react-native/issues/14209)

**Comment by koenpunt** [comment]
Let me check, I didn't experience any issues on Android or iOS though.

**Comment by koenpunt** [comment]
Oh but I did only test with the version of react-native being used in the example, but that one is pretty outdated. I could update the example too?

**Comment by koenpunt** [comment]
Works for me on both platforms with the latest React-Native too:

**Comment by koenpunt** [comment]
See my latest commit for an updated `Example` app

**Comment by koenpunt** [comment]
I've now also removed the barcodes directory from the repository, and added JsBarcode as a dependency to use their encoders directly.

**Comment by wonsikin** [comment]
@koenpunt I do think that you are a genius.I'll check the example, if OK, I will publish this package.

**Comment by koenpunt** [comment]
Great 🚀 I will submit some more patches the upcoming time, particularly one for EAN(13) barcodes, since they now do not render when `flat` is not set to false. This went wrong also before my changes.

**Comment by wonsikin** [comment]
I'll appreciate your patches!

**Pull request merged**
